creation_rules:
  - path_regex: '(\.env(\.enc)?(\.safe)?$)'
    #encrypted_regex: '^(APP_KEY|DB_|MAIL_|API_|.*PASSWORD|.*SECRET).*='
    encrypted_regex: '^(APP_KEY|DB_.*|MAIL_.*|.*PASSWORD.*|.*SECRET.*)$'
    age: |
      age1d2kzfwyfcqu3wgrgamchlgezfdxaq0cfgncq7ylu20ytvsqsd5uqjs7yp7


# Set-ExecutionPolicy RemoteSigned -scope CurrentUser
# irm get.scoop.sh | iex
# scoop bucket add main
# scoop bucket add extras
# scoop install sops
# scoop install sops age
# sops --version
# age --version

# New-Item -ItemType Directory -Path "$env:APPDATA\sops\age" -Force
# age-keygen | Out-File -Encoding ascii "$env:APPDATA\sops\age\keys.txt"
# age-keygen.exe -o $HOME\.config\sops\age\keys.txt  --- alternativa al precedente, occhio ai path
# type "$env:APPDATA\sops\age\keys.txt"
# sops --encrypt --input-type dotenv --output-type dotenv --output .env.enc .env
# sops --decrypt --input-type dotenv --output-type dotenv --output .env .env.enc
